# Generated by Django 5.1.5 on 2025-02-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='A URL-friendly version of the name.'),
        ),
    ]
