# Generated by Django 5.1.5 on 2025-02-28 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_alter_hub_slug'),
        ('utils', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hub',
            field=models.ForeignKey(blank=True, help_text='If set, this category is specific to a hub; if null, it’s global.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='hubs.hub'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='hubs.hub'),
        ),
    ]
