# Generated by Django 5.1.5 on 2025-02-28 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_alter_hub_slug'),
        ('utils', '0003_alter_category_hub_alter_tag_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='hubs.hub'),
        ),
    ]
