# Generated by Django 5.1.5 on 2025-03-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_searchhistory_hub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(help_text='Content for description meta tag', max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(help_text='Comma delimited set of SEO keywords for meta tag', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
    ]
